In [2080]:
#Loading tpdata

import numpy as np
import pandas as pd
import esig
tpdata=pd.read_csv("ADNI/tpdata.csv",header=None)

In [2081]:
#Loading the tables with AD,MCI, NL people

#mci=pd.read_csv("ADNI/mcirids.csv",header=None)
#nl=pd.read_csv("ADNI/nlrids.csv",header=None)
ad=pd.read_csv("ADNI/adrids.csv",header=None)

In [2082]:
#Eliiminating measurements of month 3 in AD people
#rows_ad = tpdata[tpdata[0].isin(ad.values.flatten())]
#row_ad_with_month_equal_3 = rows_ad[rows_ad[3]==3]
#tpdata.drop(row_ad_with_month_equal_3.index,inplace=True)

#Eliminating measurement of month 3 in AD people
rows_ad=tpdata[tpdata[4]==3]
rows_ad_with_month_equal_3=rows_ad[rows_ad[3]==3]
tpdata.drop(row_ad_with_month_equal_3.index,inplace=True)

In [2083]:
#For each person, sorting its values according to the month of measurement, and classifying it into one of the three groups


#labels = np.empty(shape=len(tpdata), dtype=object)

#for individual in mci.values.flatten():
    #individual_index_mci = np.where(tpdata[0]==individual)[0]
    #labels[individual_index_mci]="mci"
    #tpdata.iloc[individual_index_mci].sort_values(by=3)
    
#for individual in nl.values.flatten():
    #individual_index_nl=np.where(tpdata[0]==individual)[0]
    #labels[individual_index_nl]="nl"
    #tpdata.iloc[individual_index_nl].sort_values(by=3)
    
#for individual in ad.values.flatten():
    #individual_index_ad=np.where(tpdata[0]==individual)[0]
    #labels[individual_index_ad]="ad"
    #tpdata.iloc[individual_index_ad].sort_values(by=3)

#tpdata.insert(168, "Labels", labels, True)


#Sorting rows for each individual
tpdata1=tpdata.iloc[:,0]
values=set(tpdata1.values.flatten())
for individual in values:
    individual_index=np.where(tpdata.iloc[:,0]==individual)[0]
    if len(individual_index)>0:
        tpdata.iloc[individual_index_ad].sort_values(by=3)




#Eliminating months excedding 24
exceeding_months_indexes=np.where(tpdata[3]>24)[0]
rows_exceeding=tpdata[tpdata[3]>24]
tpdata.drop(rows_exceeding.index,inplace=True)


#eliminating non classified people
non_class_indexes=np.where(tpdata[4]==0)[0]
rows_non_class=tpdata[tpdata[4]==0]
tpdata.drop(rows_non_class.index,inplace=True)

In [2084]:
#Selecting only the columns of: 
tpdata=tpdata.iloc[:,[0,4,5,21,22,33]]
tpdata.columns=["Individual", "Type","Measurement","Hippocampal Volume", "Brain Volume", "Ventricle Volume"]

In [2085]:
#Normalizing values


tpdata.iloc[:,3]=tpdata.iloc[:,3]/10000
tpdata.iloc[:,5]=tpdata.iloc[:,5]/100000
tpdata.iloc[:,4]=tpdata.iloc[:,4]/1000000

In [2086]:
tpdata=tpdata.dropna()

In [2087]:
tpdata1=tpdata.iloc[:,0]
values=set(tpdata.values.flatten())
for individual in values:
    individual_index=np.where(tpdata.iloc[:,0]==individual)[0]
    if len(individual_index)>0:
        tpdata.iloc[individual_index,2]=(tpdata.iloc[individual_index,2]-tpdata.iloc[individual_index[0],2])/30

In [2088]:
tpdata

,Individual,Type,Measurement,Hippocampal Volume,Brain Volume,Ventricle Volume
0,2,1,0.000000,0.8336,1.22970,1.18230
1,3,3,0.000000,0.5319,1.12980,0.84599
2,3,3,0.198907,0.5446,1.10010,0.88580
3,3,3,0.398900,0.5157,1.09560,0.90099
4,3,3,0.797800,0.5139,1.08860,0.97420
...,...,...,...,...,...,...
12269,5273,2,0.804367,0.5932,0.90233,0.56317
12270,5277,1,0.801100,0.6456,0.98039,0.29814
12275,5290,1,0.805467,0.7424,1.01020,0.12472
12276,5292,1,0.805467,0.6918,0.98061,0.17160
12314,5263,1,0.896167,0.5059,1.12080,0.49475

In [2089]:
big_individuals=[]
for individual, individual_data in tpdata.groupby("Individual"):
    if len(individual_data)>3:
        big_individuals.append(individual)

In [2090]:
newdata=tpdata[tpdata["Individual"].isin(big_individuals)]

In [2091]:
not2=[]
for individual, individual_data in newdata.groupby("Individual"):
    if ( not (individual_data.iloc[:,1]==2).any()):
        not2.append(individual)

In [2092]:
newdata2=newdata[newdata["Individual"].isin(not2)]

In [2093]:
newdata2

,Individual,Type,Measurement,Hippocampal Volume,Brain Volume,Ventricle Volume
1,3,3,0.000000,0.5319,1.1298,0.84599
2,3,3,0.198907,0.5446,1.1001,0.88580
3,3,3,0.398900,0.5157,1.0956,0.90099
4,3,3,0.797800,0.5139,1.0886,0.97420
10,5,1,0.000000,0.7075,1.1166,0.34062
...,...,...,...,...,...,...
11275,4632,1,0.812033,0.7744,1.1491,0.48080
11380,4832,1,0.863400,0.7711,1.1250,0.41482
11766,5079,1,0.797800,0.7710,1.1716,0.29127
11774,5093,1,0.787967,0.6451,1.0452,0.19656
11780,5082,1,0.800000,0.7531,1.0488,0.34874

In [2039]:
labels=[]
Feature_vectors_sig=list()
for individual, individual_data in newdata.groupby("Individual"):
    individual_timeseries=individual_data.iloc[:,[2,3,4,5]].to_numpy()
    individual_signature=esig.stream2sig(individual_timeseries,2)[1:]
    individual_baseline=individual_timeseries[0][[1,2,3]]
    individual_feature_vector=np.concatenate([individual_baseline,individual_signature])
    individual_feature_vector[3:]=individual_feature_vector[3:]*10
    individual_feature_vector[[0,1,2]]=individual_feature_vector[[0,1,2]]
    Feature_vectors_sig.append(individual_feature_vector)
    labels.append(individual_data.iloc[0,1])

In [2040]:
#labels

In [2041]:
Feature_vectors_sig_matrix=np.array(Feature_vectors_sig)

In [2042]:
Feature_vectors_sig_matrix

array([[ 5.31900000e-01,  1.12980000e+00,  8.45990000e-01, ...,
        -1.28210000e-02, -1.44573600e-02,  8.21890205e-02],
       [ 6.86900000e-01,  1.15500000e+00,  3.96050000e-01, ...,
        -5.80032000e-03, -3.71900000e-03,  1.59556005e-02],
       [ 7.07500000e-01,  1.11660000e+00,  3.40620000e-01, ...,
        -1.82655250e-02, -1.17953300e-02,  2.88344180e-02],
       ...,
       [ 7.85600000e-01,  1.18630000e+00,  2.77420000e-01, ...,
        -1.08875500e-03, -3.82900000e-04,  9.59112500e-04],
       [ 7.96200000e-01,  1.07360000e+00,  3.31110000e-01, ...,
        -4.71696500e-03, -1.96957500e-03,  1.55408450e-03],
       [ 6.20800000e-01,  1.04180000e+00,  1.90300000e-01, ...,
         2.23275000e-04, -4.32450000e-05,  1.95938000e-04]])

In [2043]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2044]:
#Separate data into train and test
X_train, X_test, y_train, y_test=train_test_split(Feature_vectors_sig_matrix,labels,test_size=0.33)

In [2045]:
# Train model on X_train
clf=RandomForestClassifier().fit(X_train,y_train)

#Predict Labels of X_test
y_predicted=clf.predict(X_test)


#Compare predicted labels with y
accuracy_score(y_test,y_predicted)

0.5984555984555985

In [2046]:
lab_log=[]
Feataure_vectors_log=list()
for individual, individual_data in newdata.groupby("Individual"):
    individual_timeseries=individual_data.iloc[:,[2,3,4,5]].to_numpy()
    individual_signature=esig.stream2logsig(individual_timeseries,2)
    individual_baseline=individual_timeseries[0][[1,2,3]]
    individual_feature_vector=np.concatenate([individual_baseline,individual_signature])
    Feature_vectors_log.append(individual_feature_vector)
    lab_log.append(individual_data.iloc[0,1])

Feat_log=np.array(Feature_vectors_sig)
Feat_log

array([[ 5.31900000e-01,  1.12980000e+00,  8.45990000e-01, ...,
        -1.28210000e-02, -1.44573600e-02,  8.21890205e-02],
       [ 6.86900000e-01,  1.15500000e+00,  3.96050000e-01, ...,
        -5.80032000e-03, -3.71900000e-03,  1.59556005e-02],
       [ 7.07500000e-01,  1.11660000e+00,  3.40620000e-01, ...,
        -1.82655250e-02, -1.17953300e-02,  2.88344180e-02],
       ...,
       [ 7.85600000e-01,  1.18630000e+00,  2.77420000e-01, ...,
        -1.08875500e-03, -3.82900000e-04,  9.59112500e-04],
       [ 7.96200000e-01,  1.07360000e+00,  3.31110000e-01, ...,
        -4.71696500e-03, -1.96957500e-03,  1.55408450e-03],
       [ 6.20800000e-01,  1.04180000e+00,  1.90300000e-01, ...,
         2.23275000e-04, -4.32450000e-05,  1.95938000e-04]])

In [2047]:
#Separate data into train and test
X_train_log, X_test_log, y_train_log, y_test_log=train_test_split(Feat_log,lab_log,test_size=0.2)

# Train model on X_train
clf=RandomForestClassifier().fit(X_train_log,y_train_log)

#Predict Labels of X_test
y_predicted_log=clf.predict(X_test_log)


#Compare predicted labels with y
accuracy_score(y_test_log,y_predicted_log)

0.5923566878980892

In [2048]:
labels2=[]
Feature_vectors_sig2=list()
for individual, individual_data in newdata2.groupby("Individual"):
    individual_timeseries=individual_data.iloc[:,[2,3,4,5]].to_numpy()
    individual_signature=esig.stream2sig(individual_timeseries,2)[1:]
    individual_baseline=individual_timeseries[0][[1,2,3]]
    individual_feature_vector=np.concatenate([individual_baseline,individual_signature])
    Feature_vectors_sig2.append(individual_feature_vector)
    labels2.append(individual_data.iloc[0,1])
Feat2=np.array(Feature_vectors_sig2)

In [2049]:
#Separate data into train and test
X_train2, X_test2, y_train2, y_test2=train_test_split(Feat2,labels2,test_size=0.33)
# Train model on X_train
clf=RandomForestClassifier().fit(X_train2,y_train2)

#Predict Labels of X_test
y_predicted2=clf.predict(X_test2)


#Compare predicted labels with y
accuracy_score(y_test2,y_predicted2)

0.9578947368421052

In [2050]:
labels2

[3,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 3,
 1,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 3,
 3,
 1,
 3,
 3,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 3,
 1,
 1,
 3,
 1,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1]

In [2051]:
not1=[]
for individual, individual_data in newdata.groupby("Individual"):
    if ( not (individual_data.iloc[:,1]==1).any()) :
        not1.append(individual)
        
newdata1=newdata[newdata["Individual"].isin(not1)]
newdata1

,Individual,Type,Measurement,Hippocampal Volume,Brain Volume,Ventricle Volume
1,3,3,0.000000,0.5319,1.12980,0.84599
2,3,3,0.198907,0.5446,1.10010,0.88580
3,3,3,0.398900,0.5157,1.09560,0.90099
4,3,3,0.797800,0.5139,1.08860,0.97420
5,4,2,0.000000,0.6869,1.15500,0.39605
...,...,...,...,...,...,...
12331,4311,2,1.640433,0.5526,1.01840,0.37990
12332,4312,2,1.639333,0.7150,1.04260,0.26719
12366,4404,2,1.605467,0.5820,0.90138,0.35534
12370,4324,3,1.691800,0.4570,0.78194,0.83182
12484,4115,2,1.746433,0.8404,1.11100,0.30258

In [2062]:
labels1=[]
Feature_vectors_sig1=list()
for individual, individual_data in newdata1.groupby("Individual"):
    individual_timeseries=individual_data.iloc[:,[2,3,4,5]].to_numpy()
    individual_signature=esig.stream2sig(individual_timeseries,2)[1:]
    individual_baseline=individual_timeseries[0][[1,2,3]]
    individual_feature_vector=np.concatenate([individual_baseline,individual_signature])
    Feature_vectors_sig1.append(individual_feature_vector)
    labels1.append(individual_data.iloc[0,1])
Feat1=np.array(Feature_vectors_sig1)

In [2063]:
#Separate data into train and test
X_train1, X_test1, y_train1, y_test1=train_test_split(Feat1,labels1,test_size=0.33)
# Train model on X_train
clf=RandomForestClassifier().fit(X_train1,y_train1)

#Predict Labels of X_test
y_predicted1=clf.predict(X_test1)


#Compare predicted labels with y
accuracy_score(y_test1,y_predicted1)

0.901840490797546